# Generated by Django 2.2.9 on 2020-01-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="test",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
