# Generated by Django 2.2.9 on 2020-01-06 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0005_auto_20200106_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="testh",
            field=models.ManyToManyField(
                blank=True, related_name="test_testh", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
