# Generated by Django 2.2.9 on 2020-01-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_test_testh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='many',
        ),
    ]
