# Generated by Django 2.2.9 on 2020-01-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_customtext_testtt"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="test",),
        migrations.RemoveField(model_name="customtext", name="testtt",),
    ]
