# Generated by Django 2.2.9 on 2020-01-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200106_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='one',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='testh',
        ),
        migrations.RemoveField(
            model_name='test',
            name='ttest',
        ),
    ]
